eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8222
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        lower-case-service-id: true
      routes:
        - id: products
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter
        - id: users
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter
        - id: carts
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/carts/**
          filters:
            - AuthenticationFilter
        - id: orders
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter
        - id: promotions
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/promotions/**
          filters:
            - AuthenticationFilter
        - id: payments
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/payments/**
        - id: shipping
          uri: http://localhost:8087
            - Path=/api/v1/shippings/**
          filters:
            - AuthenticationFilter

        - id: notification
          uri: http://localhost:8089
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - AuthenticationFilter
management:
  tracing:
    sampling:
      probability: 1.0
  cors:
    allowed-origins: "http://localhost:3000"  # Adjust this value to match your frontend origin
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allowed-headers: "*"  # You can customize this based on your needs
    allow-credentials: true
