eureka:
  instance:
    hostname: order-service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
server:
  port: 8085
spring:
  application:
    name: Order-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://order-mysql:3306/orderdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

application:
  config:
    orders-url: http://order-service:8222/api/v1/orders

management:
  tracing:
    sampling:
      probability: 1.0
